apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}


